### ISSUE TITLE
full of syntax errors fix it please!!!

### ISSUE THREAD

**Issue by hackverd** [Hassan-Tahir/faitagram#3]
Traceback (most recent call last):
  File "faitagram", line 8, in <module>
    from pyvirtualdisplay import Display
  File "/home/rooty/.local/lib/python2.7/site-packages/pyvirtualdisplay/__init__.py", line 4, in <module>
    from pyvirtualdisplay.display import Display
  File "/home/rooty/.local/lib/python2.7/site-packages/pyvirtualdisplay/display.py", line 26
    backend: Optional[str] = None,
           ^
SyntaxError: invalid syntax

**Comment by thehassantahir** [comment]
Hey Hackverd,

I can see you are using python2.7
`File "/home/rooty/.local/lib/python2.7/site-packages/pyvirtualdisplay/init.py"`

The program is obsolete for python2 please use python of 3.2 - 3.6 version to avoid the errors.
We are working on it make it work for new python versions.

Moreover, 
If you want to brute force Facebook only, we have our working application for python3 [FACEBOOM](https://github.com/thehassantahir/Faceboom) more user-friendly & updated.

Happy Hacking!

**Comment by hackverd** [comment]
thanks for fast and helpful reply but faceboom missing for delay option..please add it on the next update
